#ifndef MYMATHLIBRARY_GLOBAL_H
#define MYMATHLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MYMATHLIBRARY_LIBRARY)
#define MYMATHLIBRARY_EXPORT Q_DECL_EXPORT
#else
#define MYMATHLIBRARY_EXPORT Q_DECL_IMPORT
#endif

#endif // MYMATHLIBRARY_GLOBAL_H
